### ISSUE TITLE
Found an issue, have a fix

### ISSUE THREAD

**Issue by mgaffin** [AllenBurgett/hangouts_takeout_to_backupandrestore#5]
So I was getting the following error:

```
Traceback (most recent call last):
  File ".\jsontoxml.py", line 298, in <module>
    main()
  File ".\jsontoxml.py", line 291, in main
    count += singlePath(root, thread)
  File ".\jsontoxml.py", line 48, in singlePath
    text = getMessage(msg)
  File ".\jsontoxml.py", line 229, in getMessage
    name = attachment['embed_item']['thing_v2']['name']
KeyError: 'name'
```

To fix this I had to update line 229 from 
```                   
                    name = attachment['embed_item']['thing_v2']['name']
```
to
```
                    if "name" in attachment['embed_item']['thing_v2']:
                        name = attachment['embed_item']['thing_v2']['name']
                    else:
                        name = "NO NAME FOUND"
```

Hope this helps! (You could change "NO NAME FOUND" to just blank, but I was curious to see where this would show up)

**Comment by AllenBurgett** [comment]
Want to commit your fix?
